### ISSUE TITLE
The difference between the original and proposed dynamic routing algorithm

### ISSUE THREAD

**Issue by aikikia** [lalonderodney/SegCaps#1]
Hi, I read your paper. And what the most impressed me is the modification of the dynamic routing algorithm. 

You said, "We propose two modifications to the original dynamic routing algorithm where (i) children
are only routed to parents within a defined spatially-local window and (ii) transformation
matrices are shared for each member of the grid within a capsule type."

However, your code about the dynamic routing is as same as the code of the original capsule network. 
So I wonder where are the differences?

**Comment by ds2268** [comment]
@aikikia The dynamic routing algorithm is the same, that is correct. The only difference is what is the input. In the original method the input to a specific parent capsule is computed with all the children capsules, each child capsule has it's own weight matrix. In this work, input to the parent capsule are only child capsules within the predefined kernel and also all the child capsules (within kernel) within the same capsule type share the same weight matrix. 
So the method for computing routing coefficients is the same, just the input is different.

@lalonderodney that's my understanding, without reviewing the code. 

Btw. Thank you for the code and personal notification.

**Comment by lalonderodney** [comment]
@ds2268,
@aikikia is exactly right. Thank you for the great explanation. These changes allow us to use the same method for computing the coefficients but what is being routed, and how we share the transformation matrices, is what is changed.
