### ISSUE TITLE
main.py: error: argument --data_root_dir is required,  how to solve this issue.. seeking help. Regards

### ISSUE THREAD

**Issue by nooriahmed** [lalonderodney/SegCaps#10]

**Comment by Cheng-Lin-Li** [comment]
Hi nooriahmed,

According to my understanding, you have to indicate your data folder to the program by the parameter of --data_root_dir.

**Comment by lalonderodney** [comment]
Hello nooriahmed,

To be specific, as stated in the README, you are required to provide the path to your data_root_directory, this is any directory you want, where you are keeping your data stored. Inside that directory you should have two folders named 'imgs' and 'masks'. The images in 'imgs' must have the exact same name as the masks in 'masks', this allows the program to match which image and mask belong together. Hope that helps. Sorry if the README wasn't clear enough about this.
