### ISSUE TITLE
what is train_split_0.csv?

### ISSUE THREAD

**Issue by primasanjaya** [lalonderodney/SegCaps#13]
how to prepare this file? what is inside this file?

**Comment by shi18** [comment]
I have the similar question. What kind of information was saved on train_list? Thanks!

**Comment by lalonderodney** [comment]
You do not need to prepare this file. The code takes care of that for you. Simply have a set of images and masks in folders named 'imgs' and 'masks' within a folder, then give that folder path as --data_root_dir, then the program will find and generate the training split csv files which are used for cross-validation experiments. If you wish to prepare this manually, it is the basename (i.e. just the filename, no path) of the files within 'imgs' and 'masks' (which must be named the same in each folder to know how to match which image to which mask).
