### ISSUE TITLE
What is the meaning of slice in the argument?

### ISSUE THREAD

**Issue by jeongHwarr** [lalonderodney/SegCaps#15]
I do not know what slice is. I understand that the slice information in the argument is in the shape of the network. If I want to apply your network to my image data, can I put the number of channels in the image instead of slice? 

Thank you for your project. Have a nice day!

**Comment by lalonderodney** [comment]
A "slice" of a 3D medical scan is a 2D plane taken from the 3D image, typically this refers to the axial plane. You should be able to replace slices with channels but you might need to change the output of the reconstruction to be multi-channel as well. Maybe take a look at https://github.com/Cheng-Lin-Li/SegCaps if you run into trouble.
