### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by ImMrMa** [lalonderodney/SegCaps#17]
Hi,I just want to use the luna 16 data to get the same performance as yours.But I don't find how you deal the raw dataset to imgs.Would you like tell me a little about it?

**Comment by lalonderodney** [comment]
Hello @ImMrMa ,
You should be able to download the LUNA16 images and masks from the website, and simply place them into folders named 'imgs' and 'masks' within the same directory (making sure the images and masks share the same names in each folder so they can be matched up).

**Comment by ImMrMa** [comment]
I'm sorry about it,from the web I only find the 3d CT data. Where can I find it? Thank you very much for your reply!

**Comment by lalonderodney** [comment]
Yes the code takes the 3D CT data. You can download it from here: https://luna16.grand-challenge.org/download/

**Comment by ImMrMa** [comment]
Can I directly download the images and masks dataset.It would be hard for me to handle the 3d CT.

**Comment by lalonderodney** [comment]
I do not understand what you mean by directly download the "images". The images are 3D CT scans. These are medical scans not RGB images and my code is written specifically for handling 3D medical scans, not 2D "images" (or rather 2D axial slices of the CT scans). If you wish to work on RGB images I recommend you see this GitHub: https://github.com/Cheng-Lin-Li/SegCaps.

**Comment by ImMrMa** [comment]
Thank you very much.I download the 3d data,I find your code to handle the 3d data
but I don't know how to use it...I will try the rgb data in the work. sorry to disturb you.😅😅

**Comment by ImMrMa** [comment]
1:~/my_code/luna16$ ls
CSVFILES  subset1  subset3  subset5  subset7  subset9
subset0   subset2  subset4  subset6  subset8
I download the luna16 3d data. And above is the structure of the dataset.

    with open(join(root, 'split_lists', 'train_split_' + str(split) + '.csv'), 'rb') as f:
        reader = csv.reader(f)
        training_list = list(reader)

    with open(join(root, 'split_lists', 'test_split_' + str(split) + '.csv'), 'rb') as f:
        reader = csv.reader(f)
        testing_list = list(reader)
It don't contain the two files.Would you like to tell me where to find it?

**Comment by lalonderodney** [comment]
Please follow the README.

Dataset Structure
Inside the data root folder (i.e. where you have your data stored) you should have two folders: one called imgs and one called masks. All models, results, etc. are saved to this same root directory.

Main File
From the main file (main.py) you can train, test, and manipulate the segmentation capsules of various networks. Simply set the --train, --test, or --manip flags to 0 or 1 to turn these off or on respectively. The argument --data_root_dir is the only required argument and should be set to the directory containing your imgs and masks folders. There are many more arguments that can be set and these are all explained in the main.py file.

These split lists files are created by the code.

**Comment by pomodoromjy** [comment]
Sorry to bother you.I  downloaded the dataset，and found it contains .mhd files and .raw files,are they belong to imgs?So what is masks should contain?

**Comment by ImMrMa** [comment]
I want say this question too.

**Comment by lalonderodney** [comment]
The images are split into two files. The .mhd files contain the header information and the .raw files contain the image information. Both are needed. Simply place these both files together into the imgs or masks folders and the code will find the .mhd files and read in the .raw files from these.
