### ISSUE TITLE
Implementation in Pytorch

### ISSUE THREAD

**Issue by ierosodin** [lalonderodney/SegCaps#18]
Hi, I'm wondering if there is any implementation in Pytorch version?
I also do some research about segmentation and want to test SegCaps performance in our dataset

**Comment by lalonderodney** [comment]
Hello @ierosodin ,
I do not have an official implementation in Pytorch although I have heard from a few fellow researchers who were working on Pytorch implementations. You might try contacting the first author on the following paper (https://openreview.net/forum?id=rJen0zC1lE) to see if they will be making their code public. I have spoken with Cher who said their implementation is in Pytorch, but as this work is not yet published I do not know when or if they will make the code public. You might also post on the following GitHub (https://github.com/Cheng-Lin-Li/SegCaps) and see if anyone there knows of a Pytorch implementation.

**Comment by ImMrMa** [comment]
I‘m writing the pytorch version.
But some problems remain unsolved.
If you want to work with it ,you can contact me.

**Comment by ierosodin** [comment]
> Hello @ierosodin ,
> I do not have an official implementation in Pytorch although I have heard from a few fellow researchers who were working on Pytorch implementations. You might try contacting the first author on the following paper (https://openreview.net/forum?id=rJen0zC1lE) to see if they will be making their code public. I have spoken with Cher who said their implementation is in Pytorch, but as this work is not yet published I do not know when or if they will make the code public. You might also post on the following GitHub (https://github.com/Cheng-Lin-Li/SegCaps) and see if anyone there knows of a Pytorch implementation.

Thanks a lot for this information.

**Comment by ierosodin** [comment]
> I‘m writing the pytorch version.
> But some problems remain unsolved.
> If you want to work with it ,you can contact me.

Sure, maybe I can take a look and work together. (I also send you a email)

**Comment by ImMrMa** [comment]
I have finished the pytorch version.
https://github.com/ImMrMa/SegCaps.pytorch

**Comment by John1231983** [comment]
Great ImMrMa. It is nice to see comparision between official version and pytorch. I also love pytorch too

**Comment by ImMrMa** [comment]
I don't have the dataset,you can test it by yourself.I'd like to see the result too.




| |
haha
邮箱：ma870587394@163.com
|

Signature is customized by Netease Mail Master

On 02/27/2019 13:14, John1231983 wrote:

Great ImMrMa. It is nice to see comparision between official version and pytorch. I also love pytorch too

**Comment by John1231983** [comment]
Why not use same dataset with official code? Is it not available?

**Comment by ImMrMa** [comment]
I don't know how to use the dataset.The official dataset is 3d ct.Process it is hard to me.




| |
haha
邮箱：ma870587394@163.com
|

Signature is customized by Netease Mail Master

On 02/27/2019 21:30, John1231983 wrote:

Why not use same dataset with official code? Is it not available?
