### ISSUE TITLE
The training data format

### ISSUE THREAD

**Issue by yishiliuhuasheng** [lalonderodney/SegCaps#2]
Can you tell me the training data format, I want to use your model for training, but does not understand what is the format of the original data, please explain in detail. Thanks!

**Comment by lalonderodney** [comment]
@yishiliuhuasheng Hello. The images come from LUNA16 (https://luna16.grand-challenge.org/) in the .mhd and .raw format. Just create a folder called imgs and a folder called masks in the same directory (whatever directory you want, just set the path to this in main under --data_root_dir) and place the images in the one and masks in the other. You will need to go to LUNA16's website and register and download the data yourself to use it.

**Comment by yishiliuhuasheng** [comment]
It's helpful for me! Thank you very much!

**Comment by mohofar** [comment]
could you tell me about training time on luna16? and also training hardware?
