### ISSUE TITLE
Sorry to bother you.I  downloaded the dataset，and found it contains .mhd files and .raw files,are they belong to imgs?So what is masks should contain?

### ISSUE THREAD

**Issue by ImMrMa** [lalonderodney/SegCaps#24]
Sorry to bother you.I  downloaded the dataset，and found it contains .mhd files and .raw files,are they belong to imgs?So what is masks should contain?

_Originally posted by @pomodoromjy in https://github.com/lalonderodney/SegCaps/issues/17#issuecomment-470075670_

Sorry to bother you.I have the same problem with this man.I need the help to test on the dataset.

**Comment by lalonderodney** [comment]
The images are split into two files. The .mhd files contain the header information and the .raw files contain the image information. Both are needed. Simply place these both files together into the imgs or masks folders and the code will find the .mhd files and read in the .raw files from these.
