### ISSUE TITLE
default value of loss type for dice_soft

### ISSUE THREAD

**Issue by Cheng-Lin-Li** [lalonderodney/SegCaps#9]
Hi lalonderodney,

Thanks for your awesome paper and programs.
I am working on a pipeline based on your codebase to let everyone can train their own SegCaps on 3D and 2D images (MS COCO dataset). 

In the description of custom loss function "dice_soft" said default loss type is 'jaccard' but the code assign loss_type='sorensen'. I supposed 'jaccard' should be the correct default value, am I right?

Thanks for your time and clarifications.

**Comment by lalonderodney** [comment]
Hello Cheng-Lin-Li,

Sorry for the long delay. Unfortunately I have far too many projects to keep tabs on this repo. To answer your question, either loss_type is fine. Checkout the definitions of sorensen vs jaccard. I tend to prefer sorensen but I don't have a strong justification for the preference. 

Good luck working with the code. I will try to help when I can.
